spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/stamo-bot-db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
